# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build && Deploy / DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install deps && build
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        nvm use 23.6
        npm ci --legacy-peer-deps && npm run build
    - name: Deploy
      env: 
        S3: ${{ secrets.S3_DEV }}
      run: aws s3 sync ./dist ${S3} --endpoint-url=https://storage.yandexcloud.net
