# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build && Deploy / DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: npm ci --legacy-peer-deps
      shell: bash
    - name: Build 
      run: npm run build
      shell: bash
    - name: Deploy
      env: 
        S3: ${{ secrets.S3_DEV }}
      run: aws sync ./dist ${S3} --endpoint-url=https://storage.yandexcloud.net
